### ISSUE TITLE
Release to Production

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#229]
#### Task
As UAT (#202) has met bare-minimum requirements we move our focus to releasing to production. 

This will be a gradual migration allowing users to migrate at their own time. This is possible as we have tested (#209) the QGIS2 version of the plugin (version 1.8.2) will continue to operate with the minor DB change we will need to make for the QGIS3 version. 

Release involves:
- [x] Deploy the plugin to the linz prd plugin repo via CI/CD
- [x] Take a backup of production database
- [x] Deploy update to [gazetteer_geometry_views](https://github.com/linz/gazetteer/blob/master/src/sql/gazetteer_geometry_views.sql) gazetteer_geometry_views.sql)

- [x] Chris to add prd plugin url (https://plugins.qgis.linz.govt.nz/v1/plugins.xml) to his QGIS3 instance via plugin manager and install the production version to begin using. Others to follow suit after when suits.
- [x] Upgrade the plugin version reference as stored in the system_code table once all users are using QGIS3
```
UPDATE gazetteer.system_code
   SET value=2.0.4
 WHERE code = 'VRSN'
 AND value = '1.8.2'
```

#### Discussion required

* My part in this needs to be done this week but this does not mean users need to begin using QGIS3 / The new version of the plugin. A plan should be made to migrate them over however. 
* As the system_code `VRSN` version is not to be updated until all users have migrated to QGIS3, a warning will pop-up on plugin startup indicating the new plugin version does not match the DB version. Once all users have migrated to QGIS3 when will update the DB to remove this message

**Comment by billgeo** [comment]
Thanks @SPlanzer. This looks fine to me if NZGB are okay with this plan.

**Comment by SPlanzer** [comment]
@CMKMS-LINZ please review

**Comment by CMKMS-LINZ** [comment]
@billgeo I think we need to get Wendy across where it's at, though I fully understand this is it for @SPlanzer 

As mentioned here https://github.com/linz/gazetteer/issues/202#issuecomment-713143747 remaining bug #222 is quite annoying and happens frequently, but I was unable to figure out how to reproduce on demand. A timeframe to resolve this would be good.

As I understand it, fixing the existing zoom-to functionality which was broken in 2.6.1 has caused #206, as the Gazetteer geometry is in 4167 the westings cause all sorts of havoc. I don't know what the total scope of work to try and resolve this might be.

**Comment by SPlanzer** [comment]
backup taken 
```
C:\Program Files (x86)\pgAdmin III\1.20\pg_dump.exe --host prdgeo01 --port 5432 --username "splanzer" --no-password  --format custom --blobs --verbose --file "G:\gaz_porting\gaz_backup-20201029-t1540.backup" "gazetteer"
pg_dump: reading schemas
pg_dump: reading user-defined tables
pg_dump: reading extensions
pg_dump: reading user-defined functions
pg_dump: reading user-defined types
pg_dump: reading procedural languages
pg_dump: reading user-defined aggregate functions
pg_dump: reading user-defined operators
pg_dump: reading user-defined operator classes
pg_dump: reading user-defined operator families
pg_dump: reading user-defined text search parsers
pg_dump: reading user-defined text search templates
pg_dump: reading user-defined text search dictionaries
pg_dump: reading user-defined text search configurations
pg_dump: reading user-defined foreign-data wrappers
pg_dump: reading user-defined foreign servers
pg_dump: reading default privileges
pg_dump: reading user-defined collations
pg_dump: reading user-defined conversions
pg_dump: reading type casts
pg_dump: reading table inheritance information
pg_dump: reading event triggers
pg_dump: finding extension members
pg_dump: finding inheritance relationships
pg_dump: reading column info for interesting tables
pg_dump: finding the columns and types of table "spatial_ref_sys"
pg_dump: finding the columns and types of table "geometry_columns"
pg_dump: finding the columns and types of table "geography_columns"
pg_dump: finding the columns and types of table "gaz_feature"
pg_dump: finding the columns and types of table "gaz_name"
pg_dump: finding the columns and types of table "gaz_word"
pg_dump: finding the columns and types of table "gaz_shape"
pg_dump: finding default expressions of table "gaz_shape"
pg_dump: finding the columns and types of table "gaz_annotation"
pg_dump: finding default expressions of table "gaz_annotation"
pg_dump: finding the columns and types of table "gaz_web_config"
pg_dump: finding the columns and types of table "system_code"
pg_dump: finding the columns and types of table "feature"
pg_dump: finding default expressions of table "feature"
pg_dump: finding check constraints for table "feature"
pg_dump: finding the columns and types of table "feature_geometry"
pg_dump: finding default expressions of table "feature_geometry"
pg_dump: finding check constraints for table "feature_geometry"
pg_dump: finding the columns and types of table "name"
pg_dump: finding default expressions of table "name"
pg_dump: finding the columns and types of table "name_event"
pg_dump: finding default expressions of table "name_event"
pg_dump: finding the columns and types of table "feature_association"
pg_dump: finding default expressions of table "feature_association"
pg_dump: finding the columns and types of table "name_association"
pg_dump: finding default expressions of table "name_association"
pg_dump: finding the columns and types of table "feature_annotation"
pg_dump: finding default expressions of table "feature_annotation"
pg_dump: finding the columns and types of table "name_annotation"
pg_dump: finding default expressions of table "name_annotation"
pg_dump: finding the columns and types of table "app_usage"
pg_dump: finding default expressions of table "app_usage"
pg_dump: finding the columns and types of table "app_favourites"
pg_dump: finding default expressions of table "app_favourites"
pg_dump: finding the columns and types of table "feature"
pg_dump: finding default expressions of table "feature"
pg_dump: finding the columns and types of table "feature_annotation"
pg_dump: finding default expressions of table "feature_annotation"
pg_dump: finding the columns and types of table "feature_association"
pg_dump: finding default expressions of table "feature_association"
pg_dump: finding the columns and types of table "name"
pg_dump: finding default expressions of table "name"
pg_dump: finding the columns and types of table "name_event"
pg_dump: finding default expressions of table "name_event"
pg_dump: finding the columns and types of table "name_annotation"
pg_dump: finding default expressions of table "name_annotation"
pg_dump: finding the columns and types of table "name_association"
pg_dump: finding default expressions of table "name_association"
pg_dump: finding the columns and types of table "feature_geometry"
pg_dump: finding default expressions of table "feature_geometry"
pg_dump: finding the columns and types of table "system_code"
pg_dump: finding default expressions of table "system_code"
pg_dump: finding the columns and types of table "feature_ref_point"
pg_dump: finding the columns and types of table "feature_point"
pg_dump: finding the columns and types of table "feature_line"
pg_dump: finding the columns and types of table "feature_polygon"
pg_dump: finding the columns and types of table "gazetteer_users"
pg_dump: finding the columns and types of table "tmp_view_benu"
pg_dump: finding the columns and types of table "gaz_all_names_line"
pg_dump: finding the columns and types of table "gaz_all_names_poly"
pg_dump: finding the columns and types of table "name_export"
pg_dump: finding the columns and types of table "gazetteer_export_tables"
pg_dump: finding the columns and types of table "geographic_names"
pg_dump: finding default expressions of table "geographic_names"
pg_dump: finding the columns and types of table "territorial_authority_low_res"
pg_dump: finding check constraints for table "territorial_authority_low_res"
pg_dump: finding the columns and types of table "feature_bkup_04032016"
pg_dump: finding the columns and types of table "final_names_to_update"
pg_dump: finding the columns and types of table "name_export_for_lol"
pg_dump: finding the columns and types of table "gaz_all_shapes"
pg_dump: finding the columns and types of table "gaz_event"
pg_dump: finding the columns and types of table "gaz_code_backup"
pg_dump: finding the columns and types of table "gaz_code"
pg_dump: finding the columns and types of table "metadata"
pg_dump: finding default expressions of table "metadata"
pg_dump: finding the columns and types of table "metadata_reference"
pg_dump: finding default expressions of table "metadata_reference"
pg_dump: finding the columns and types of table "gaz_all_names"
pg_dump: finding the columns and types of table "gaz_names_csv"
pg_dump: finding the columns and types of table "gaz_official_names"
pg_dump: finding the columns and types of table "gaz_report_base_table"
pg_dump: finding the columns and types of table "line_export"
pg_dump: finding the columns and types of table "polygon_export"
pg_dump: finding the columns and types of table "name_export_for_lol"
pg_dump: flagging inherited columns in subtables
pg_dump: reading indexes
pg_dump: reading indexes for table "spatial_ref_sys"
pg_dump: reading indexes for table "geometry_columns"
pg_dump: reading indexes for table "gaz_feature"
pg_dump: reading indexes for table "gaz_name"
pg_dump: reading indexes for table "gaz_word"
pg_dump: reading indexes for table "gaz_shape"
pg_dump: reading indexes for table "gaz_annotation"
pg_dump: reading indexes for table "gaz_web_config"
pg_dump: reading indexes for table "system_code"
pg_dump: reading indexes for table "feature"
pg_dump: reading indexes for table "feature_geometry"
pg_dump: reading indexes for table "name"
pg_dump: reading indexes for table "name_event"
pg_dump: reading indexes for table "feature_association"
pg_dump: reading indexes for table "name_association"
pg_dump: reading indexes for table "feature_annotation"
pg_dump: reading indexes for table "name_annotation"
pg_dump: reading indexes for table "app_usage"
pg_dump: reading indexes for table "app_favourites"
pg_dump: reading indexes for table "feature"
pg_dump: reading indexes for table "feature_annotation"
pg_dump: reading indexes for table "feature_association"
pg_dump: reading indexes for table "name"
pg_dump: reading indexes for table "name_event"
pg_dump: reading indexes for table "name_annotation"
pg_dump: reading indexes for table "name_association"
pg_dump: reading indexes for table "feature_geometry"
pg_dump: reading indexes for table "system_code"
pg_dump: reading indexes for table "gaz_all_names_line"
pg_dump: reading indexes for table "gaz_all_names_poly"
pg_dump: reading indexes for table "geographic_names"
pg_dump: reading indexes for table "territorial_authority_low_res"
pg_dump: reading indexes for table "gaz_event"
pg_dump: reading indexes for table "gaz_code"
pg_dump: reading indexes for table "metadata"
pg_dump: reading indexes for table "gaz_all_names"
pg_dump: reading indexes for table "gaz_names_csv"
pg_dump: reading indexes for table "gaz_official_names"
pg_dump: reading indexes for table "gaz_report_base_table"
pg_dump: reading indexes for table "line_export"
pg_dump: reading indexes for table "polygon_export"
pg_dump: reading indexes for table "name_export_for_lol"
pg_dump: reading constraints
pg_dump: reading foreign key constraints for table "system_code"
pg_dump: reading foreign key constraints for table "feature"
pg_dump: reading foreign key constraints for table "feature_geometry"
pg_dump: reading foreign key constraints for table "name"
pg_dump: reading foreign key constraints for table "name_event"
pg_dump: reading foreign key constraints for table "feature_association"
pg_dump: reading foreign key constraints for table "name_association"
pg_dump: reading foreign key constraints for table "feature_annotation"
pg_dump: reading foreign key constraints for table "name_annotation"
pg_dump: reading triggers
pg_dump: reading triggers for table "system_code"
pg_dump: reading triggers for table "feature"
pg_dump: reading triggers for table "feature_geometry"
pg_dump: reading triggers for table "name"
pg_dump: reading triggers for table "name_event"
pg_dump: reading triggers for table "feature_association"
pg_dump: reading triggers for table "name_association"
pg_dump: reading triggers for table "feature_annotation"
pg_dump: reading triggers for table "name_annotation"
pg_dump: reading rewrite rules
pg_dump: reading large objects
pg_dump: reading dependency data
pg_dump: saving encoding = UTF8
pg_dump: saving standard_conforming_strings = off
pg_dump: saving database definition
pg_dump: dumping contents of table app_favourites
pg_dump: dumping contents of table app_usage
pg_dump: dumping contents of table feature
pg_dump: dumping contents of table feature_annotation
pg_dump: dumping contents of table feature_association
pg_dump: dumping contents of table feature_bkup_04032016
pg_dump: dumping contents of table feature_geometry
pg_dump: dumping contents of table final_names_to_update
pg_dump: dumping contents of table geographic_names
pg_dump: dumping contents of table name
pg_dump: dumping contents of table name_annotation
pg_dump: dumping contents of table name_association
pg_dump: dumping contents of table name_event
pg_dump: dumping contents of table system_code
pg_dump: dumping contents of table territorial_authority_low_res
pg_dump: dumping contents of table gaz_all_names
pg_dump: dumping contents of table gaz_names_csv
pg_dump: dumping contents of table gaz_official_names
pg_dump: dumping contents of table gaz_report_base_table
pg_dump: dumping contents of table line_export
pg_dump: dumping contents of table metadata
pg_dump: dumping contents of table metadata_reference
pg_dump: dumping contents of table name_export_for_lol
pg_dump: dumping contents of table polygon_export
pg_dump: dumping contents of table feature
pg_dump: dumping contents of table feature_annotation
pg_dump: dumping contents of table feature_association
pg_dump: dumping contents of table feature_geometry
pg_dump: dumping contents of table name
pg_dump: dumping contents of table name_annotation
pg_dump: dumping contents of table name_association
pg_dump: dumping contents of table name_event
pg_dump: dumping contents of table system_code
pg_dump: dumping contents of table gaz_all_shapes
pg_dump: dumping contents of table gaz_annotation
pg_dump: dumping contents of table gaz_code
pg_dump: dumping contents of table gaz_code_backup
pg_dump: dumping contents of table gaz_event
pg_dump: dumping contents of table gaz_feature
pg_dump: dumping contents of table gaz_name
pg_dump: dumping contents of table gaz_shape
pg_dump: dumping contents of table gaz_web_config
pg_dump: dumping contents of table gaz_word
pg_dump: dumping contents of table geometry_columns
pg_dump: dumping contents of table spatial_ref_sys
pg_dump: dumping contents of table gaz_all_names_line
pg_dump: dumping contents of table gaz_all_names_poly

Process returned exit code 0.
```

**Comment by SPlanzer** [comment]
released to production plugin repository - https://plugins.qgis.linz.govt.nz/v1/plugin/NZGBplugin
Version is v2.0.4
